// Mocks generated by Mockito 5.4.4 from annotations
// in weather_app/test/features/weather/domain/usecases/settings/open_app_location_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_app/core/resources/data_state.dart' as _i3;
import 'package:weather_app/features/weather/data/data_sources/local/settings_service.dart'
    as _i2;
import 'package:weather_app/features/weather/data/repository/settings_repository_impl.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSettingsService_0 extends _i1.SmartFake
    implements _i2.SettingsService {
  _FakeSettingsService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDataState_1<T> extends _i1.SmartFake implements _i3.DataState<T> {
  _FakeDataState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SettingsRepositoryImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsRepositoryImpl extends _i1.Mock
    implements _i4.SettingsRepositoryImpl {
  MockSettingsRepositoryImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SettingsService get settingsService => (super.noSuchMethod(
        Invocation.getter(#settingsService),
        returnValue: _FakeSettingsService_0(
          this,
          Invocation.getter(#settingsService),
        ),
      ) as _i2.SettingsService);

  @override
  _i5.Future<_i3.DataState<_i3.Unit>> openLocationSettings() =>
      (super.noSuchMethod(
        Invocation.method(
          #openLocationSettings,
          [],
        ),
        returnValue: _i5.Future<_i3.DataState<_i3.Unit>>.value(
            _FakeDataState_1<_i3.Unit>(
          this,
          Invocation.method(
            #openLocationSettings,
            [],
          ),
        )),
      ) as _i5.Future<_i3.DataState<_i3.Unit>>);

  @override
  _i5.Future<_i3.DataState<_i3.Unit>> openAppSettings() => (super.noSuchMethod(
        Invocation.method(
          #openAppSettings,
          [],
        ),
        returnValue: _i5.Future<_i3.DataState<_i3.Unit>>.value(
            _FakeDataState_1<_i3.Unit>(
          this,
          Invocation.method(
            #openAppSettings,
            [],
          ),
        )),
      ) as _i5.Future<_i3.DataState<_i3.Unit>>);
}
